### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by pixoinc** [concrete5-community-store/community_store#344]
When an order is placed I'm getting the following error message in the logs and the new order notification doesn't go out.  Are you able to reproduce this error?

Mail Exception Occurred. Unable to send mail: Unable to send mail: Unknown error
#0 [internal function]: Zend\Mail\Transport\Sendmail->mailHandler('frcr3670@gmail....', 'New Order Notif...', 'This is a messa...', 'Date: Thu, 22 F...', ' -ffrcr3670@gma...')
#1 /home/fiverivers/public_html/concrete/vendor/zendframework/zend-mail/src/Transport/Sendmail.php(138): call_user_func(Array, 'frcr3670@gmail....', 'New Order Notif...', 'This is a messa...', 'Date: Thu, 22 F...', ' -ffrcr3670@gma...')
#2 /home/fiverivers/public_html/concrete/src/Mail/Service.php(475): Zend\Mail\Transport\Sendmail->send(Object(Zend\Mail\Message))
#3 /home/fiverivers/public_html/packages/community_store/src/CommunityStore/Order/Order.php(872): Concrete\Core\Mail\Service->sendMail()
#4 /home/fiverivers/public_html/packages/community_store/src/CommunityStore/Order/Order.php(635): Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order->sendNotifications()
#5 /home/fiverivers/public_html/packages/community_store/src/CommunityStore/Order/Order.php(557): Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order->completeOrder('ch_1ByKuAFU0Yiw...', true)
#6 /home/fiverivers/public_html/packages/community_store/controllers/single_page/checkout.php(243): Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order::add(Object(Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method), 'ch_1ByKuAFU0Yiw...')
#7 [internal function]: Concrete\Package\CommunityStore\Controller\SinglePage\Checkout->submit()
#8 /home/fiverivers/public_html/concrete/src/Controller/AbstractController.php(172): call_user_func_array(Array, Array)
#9 /home/fiverivers/public_html/concrete/src/Http/ResponseFactory.php(182): Concrete\Core\Controller\AbstractController->runAction('submit', Array)
#10 /home/fiverivers/public_html/concrete/src/Http/ResponseFactory.php(369): Concrete\Core\Http\ResponseFactory->controller(Object(Concrete\Package\CommunityStore\Controller\SinglePage\Checkout))
#11 /home/fiverivers/public_html/concrete/src/Routing/DispatcherRouteCallback.php(34): Concrete\Core\Http\ResponseFactory->collection(Object(Concrete\Core\Page\Page))
#12 /home/fiverivers/public_html/concrete/src/Http/DefaultDispatcher.php(122): Concrete\Core\Routing\DispatcherRouteCallback->execute(Object(Concrete\Core\Http\Request))
#13 /home/fiverivers/public_html/concrete/src/Http/DefaultDispatcher.php(54): Concrete\Core\Http\DefaultDispatcher->handleDispatch(Object(Concrete\Core\Http\Request))
#14 /home/fiverivers/public_html/concrete/src/Http/Middleware/DispatcherDelegate.php(39): Concrete\Core\Http\DefaultDispatcher->dispatch(Object(Concrete\Core\Http\Request))
#15 /home/fiverivers/public_html/concrete/src/Http/Middleware/ThumbnailMiddleware.php(60): Concrete\Core\Http\Middleware\DispatcherDelegate->next(Object(Concrete\Core\Http\Request))
#16 /home/fiverivers/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php(38): Concrete\Core\Http\Middleware\ThumbnailMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\DispatcherDelegate))
#17 /home/fiverivers/public_html/concrete/src/Http/Middleware/FrameOptionsMiddleware.php(39): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request))
#18 /home/fiverivers/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php(38): Concrete\Core\Http\Middleware\FrameOptionsMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate))
#19 /home/fiverivers/public_html/concrete/src/Http/Middleware/CookieMiddleware.php(37): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request))
#20 /home/fiverivers/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php(38): Concrete\Core\Http\Middleware\CookieMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate))
#21 /home/fiverivers/public_html/concrete/src/Http/Middleware/ApplicationMiddleware.php(29): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request))
#22 /home/fiverivers/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php(38): Concrete\Core\Http\Middleware\ApplicationMiddleware->process(Object(Concrete\Core\Http\Request), Object(Concrete\Core\Http\Middleware\MiddlewareDelegate))
#23 /home/fiverivers/public_html/concrete/src/Http/Middleware/MiddlewareStack.php(86): Concrete\Core\Http\Middleware\MiddlewareDelegate->next(Object(Concrete\Core\Http\Request))
#24 /home/fiverivers/public_html/concrete/src/Http/DefaultServer.php(85): Concrete\Core\Http\Middleware\MiddlewareStack->process(Object(Concrete\Core\Http\Request))
#25 /home/fiverivers/public_html/concrete/src/Foundation/Runtime/Run/DefaultRunner.php(115): Concrete\Core\Http\DefaultServer->handleRequest(Object(Concrete\Core\Http\Request))
#26 /home/fiverivers/public_html/concrete/src/Foundation/Runtime/DefaultRuntime.php(102): Concrete\Core\Foundation\Runtime\Run\DefaultRunner->run()
#27 /home/fiverivers/public_html/concrete/dispatcher.php(39): Concrete\Core\Foundation\Runtime\DefaultRuntime->run()
#28 /home/fiverivers/public_html/index.php(3): require('/home/fiveriver...')
#29 {main}

**Comment by pixoinc** [comment]
I should mention, that the contact forms on the site using the Form block work find and default SMTP settings are in place.

**Comment by Mesuva** [comment]
The email you've configured to send emails to, is it free of whitespace at the end?
I'd also check that the Sent From email address is valid too, and is allowed to send emails from your server. 

(there should be some whitespace trimming of the emails, but I wouldn't be surprised if that's been overlooked)

**Comment by pixoinc** [comment]
Thanks for your quick reply.  I’ve checked and there is no extra spaces
before or after the email address in the Send to or the Email Sent From
fields.





*From:* Ryan Hewitt [mailto:notifications@github.com]
*Sent:* Thursday, February 22, 2018 3:08 PM
*To:* concrete5-community-store/community_store <
community_store@noreply.github.com>
*Cc:* pixoinc <jamie@pixoinc.com>; Author <author@noreply.github.com>
*Subject:* Re: [concrete5-community-store/community_store] Email Error
(#344)



The email you've configured to send emails to, is it free of whitespace at
the end?
I'd also check that the Sent From email address is valid too, and is
allowed to send emails from your server.

(there should be some whitespace trimming of the emails, but I wouldn't be
surprised if that's been overlooked)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/concrete5-community-store/community_store/issues/344#issuecomment-367839042>,
or mute the thread

**Comment by pixoinc** [comment]
I’ve got it working now, but I’m not sure why.  It does appear to have been
something with the email address.  I changed the email address to another
one and the email went out.  I then changed it back to the original email
address and then tested again and the email went out, so I’m not sure what
was wrong, but it seems to be working now.



*From:* Ryan Hewitt [mailto:notifications@github.com]
*Sent:* Thursday, February 22, 2018 3:08 PM
*To:* concrete5-community-store/community_store <
community_store@noreply.github.com>
*Cc:* pixoinc <jamie@pixoinc.com>; Author <author@noreply.github.com>
*Subject:* Re: [concrete5-community-store/community_store] Email Error
(#344)



The email you've configured to send emails to, is it free of whitespace at
the end?
I'd also check that the Sent From email address is valid too, and is
allowed to send emails from your server.

(there should be some whitespace trimming of the emails, but I wouldn't be
surprised if that's been overlooked)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/concrete5-community-store/community_store/issues/344#issuecomment-367839042>,
or mute the thread
